# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1006, 713)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(360, 50, 121, 71))
        self.button1.setObjectName("button1")
        self.output_box_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.output_box_1.setGeometry(QtCore.QRect(520, 10, 431, 201))
        self.output_box_1.setObjectName("output_box_1")
        self.graph_widget = PlotWidget(self.centralwidget)
        self.graph_widget.setGeometry(QtCore.QRect(10, 380, 971, 291))
        self.graph_widget.setObjectName("graph_widget")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(810, 310, 121, 51))
        self.button2.setObjectName("button2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 140, 451, 221))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.button3 = QtWidgets.QPushButton(self.tab)
        self.button3.setGeometry(QtCore.QRect(330, 40, 75, 24))
        self.button3.setObjectName("button3")
        self.file_location_box = QtWidgets.QPlainTextEdit(self.tab)
        self.file_location_box.setGeometry(QtCore.QRect(10, 40, 281, 61))
        self.file_location_box.setObjectName("file_location_box")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.button4 = QtWidgets.QPushButton(self.tab)
        self.button4.setGeometry(QtCore.QRect(330, 80, 75, 24))
        self.button4.setObjectName("button4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalSlider = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 70, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.tabWidget.addTab(self.tab_2, "")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(670, 330, 76, 20))
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1006, 22))
        self.menubar.setObjectName("menubar")
        self.menuHRV = QtWidgets.QMenu(self.menubar)
        self.menuHRV.setObjectName("menuHRV")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHRV.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button1.setText(_translate("MainWindow", "Run"))
        self.button2.setText(_translate("MainWindow", "Get Region"))
        self.button3.setText(_translate("MainWindow", "Browse:"))
        self.label.setText(_translate("MainWindow", "File:"))
        self.button4.setText(_translate("MainWindow", "Load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.menuHRV.setTitle(_translate("MainWindow", "HRV"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
